#define WINDOW_DEFAULT_WIDTH 1000
#define WINDOW_DEFAULT_HEIGHT 1000

#define PLAYER_GROUND 300
#define PLAYER_JUMP_PIXELS 150
#define PLAYER_MOVE_LEFT_PIXELS 10
#define PLAYER_MOVE_RIGHT_PIXELS 15

#define PLAYER_JUMP_HEIGHT 150

#define PLAYER_SPRITE_FRAMES_RUNNING 7
#define PLAYER_SPRITE_DELAY_RUNNING 0.1f

#define BACKGROUND_ZORDER -100
#define BACKGROUND_SCROLL_SPEED 250
