#define WINDOW_DEFAULT_WIDTH 1000
#define WINDOW_DEFAULT_HEIGHT 1000

#define PLAYER_GROUND 120
#define PLAYER_JUMP_PIXELS 150
#define PLAYER_MOVE_LEFT_PIXELS 10
#define PLAYER_MOVE_RIGHT_PIXELS 15

#define PLAYER_JUMP_HEIGHT 150

#define PLAYER_SPRITE_FRAMES_RUNNING 7
#define PLAYER_SPRITE_DELAY_RUNNING 0.1f
#define PLAYER_SPRITE_DELAY_WALKING 0.1f

#define BACKGROUND_ZORDER -100
#define BACKGROUND_SCROLL_SPEED 250

#define PLAYER_ANIMATION_RUNNING 1
#define PLAYER_ANIMATION_STANDING 2
#define PLAYER_ANIMATION_JUMPING 3
#define PLAYER_ANIMATION_DOUBLEJUMPING 4
#define PLAYER_ANMATION_SLIDING 5
#define PLAYER_ANIMATION_BACKWARDS 6
#define PLAYER_ANIMATION_WALKING 1
#define PLAYER_ANIMATION_DEAD 31

#define PLAYER_BULLET_LVL_1 0

#define OBJECT_SPRITE_DELAY_ANIMATION 0.1f

#define OBJECT_MAILBOX 1
#define OBJECT_ROCKET 2
#define OBJECT_FIRSTBOSS 3
#define OBJECT_FIRSTBOSS_CANNON_1 4
#define OBJECT_FIRSTBOSS_CANNON_1_D 5
#define OBJECT_BOSSBULLET_LASER 6
#define OBJECT_SPIKES 7
#define OBJECT_FIRSTBOSS_CANNON_2 8
#define OBJECT_FIRSTBOSS_CANNON_2_D 9
#define OBJECT_BOSSBULLET_SPIKEBALL 10
#define OBJECT_FIRSTBOSS_CANNON_3 11
#define OBJECT_FIRSTBOSS_CANNON_3_D 12
#define OBJECT_BOSSBULLET_BALL 13
#define OBJECT_SECONDBOSS_CANNON_1 14
#define OBJECT_SECONDBOSS_CANNON_1_D 15
#define OBJECT_BOSSBULLET_ENERGYBALL 16
#define OBJECT_SECONDBOSS_CANNON_2 17
#define OBJECT_SECONDBOSS_CANNON_2_D 18
#define OBJECT_BOSSBULLET_SAWBLADE 19
#define OBJECT_SECONDBOSS_CANNON_3 20
#define OBJECT_SECONDBOSS_CANNON_3_D 21
#define OBJECT_BOSSBULLET_FLAMEBALL 22
#define OBJECT_SECONDBOSS 23
#define OBJECT_THIRDBOSS 24
#define OBJECT_THIRDBOSS_CANNON_1 25
#define OBJECT_THIRDBOSS_CANNON_1_D 26
#define OBJECT_BOSSBULLET_BOMB 27
#define OBJECT_THIRDBOSS_CANNON_2 28
#define OBJECT_THIRDBOSS_CANNON_2_D 29
#define OBJECT_BOSSBULLET_RASENGAN 30


#define PLAYER_TAG 1010

#define GROUND_PERCENTAGE_FOR_BOX 10

#define PLAYER_COLLISION_BITMASK 1
#define MAILBOX_COLLISION_BITMASK 2
#define ROCKET_COLLISION_BITMASK 3
#define BULLET_COLLISION_BITMASK 4
#define SPIKES_COLLISION_BITMASK 5
#define BOSSBULLET_COLLISION_BITMASK 6
#define BOSS_COLLISION_BITMASK 7
#define BOSS_CANNON_COLLISION_BITMASK 8
#define GROUND_COLLISION_BITMASK 9

#define ROCKET_KILL_POINTS 30
#define MAILBOX_KILL_POINTS 10

#define LAYER_TAG 111
#define PAUSE_TAG 222