#define WINDOW_DEFAULT_WIDTH 1000
#define WINDOW_DEFAULT_HEIGHT 1000

#define PLAYER_GROUND 120
#define PLAYER_JUMP_PIXELS 150
#define PLAYER_MOVE_LEFT_PIXELS 10
#define PLAYER_MOVE_RIGHT_PIXELS 15

#define PLAYER_JUMP_HEIGHT 150

#define PLAYER_SPRITE_FRAMES_RUNNING 7
#define PLAYER_SPRITE_DELAY_RUNNING 0.1f
#define PLAYER_SPRITE_DELAY_WALKING 0.1f

#define BACKGROUND_ZORDER -100
#define BACKGROUND_SCROLL_SPEED 250

#define PLAYER_ANIMATION_RUNNING 1
#define PLAYER_ANIMATION_STANDING 2
#define PLAYER_ANIMATION_JUMPING 3
#define PLAYER_ANIMATION_DOUBLEJUMPING 4
#define PLAYER_ANMATION_SLIDING 5
#define PLAYER_ANIMATION_BACKWARDS 6
#define PLAYER_ANIMATION_WALKING 1

#define PLAYER_BULLET_LVL_1 0

#define OBJECT_SPRITE_DELAY_ANIMATION 0.1f

#define OBJECT_MAILBOX 1
#define OBJECT_ROCKET 2
#define OBJECT_FIRSTBOSS 3
#define OBJECT_FIRSTBOSS_CANNON_1 4
#define OBJECT_FIRSTBOSS_CANNON_1_D 5
#define OBJECT_BOSSBULLET_LASER 6
#define OBJECT_SPIKES 7
#define OBJECT_FIRSTBOSS_CANNON_2 8
#define OBJECT_FIRSTBOSS_CANNON_2_D 9
#define OBJECT_BOSSBULLET_SPIKEBALL 10


#define PLAYER_TAG 1010

#define GROUND_PERCENTAGE_FOR_BOX 10

#define PLAYER_COLLISION_BITMASK 1
#define MAILBOX_COLLISION_BITMASK 2
#define ROCKET_COLLISION_BITMASK 3
#define BULLET_COLLISION_BITMASK 4
#define SPIKES_COLLISION_BITMASK 5
#define BOSSBULLET_COLLISION_BITMASK 6
#define BOSS_COLLISION_BITMASK 7
#define BOSS_CANNON_COLLISION_BITMASK 8
#define GROUND_COLLISION_BITMASK 9

#define ROCKET_KILL_POINTS 30
#define MAILBOX_KILL_POINTS 10

#define LAYER_TAG 111